### ISSUE TITLE
Ragnews install packages issue to get started

### ISSUE THREAD

**Issue by maxplush** [mikeizbicki/cmc-csci181-languages#12]
I went through the steps to clone the [ragnews repo ](https://github.com/mikeizbicki/ragnews). Created a virtual environment, added my .env file with my API key - used export $(cat .env). I installed the requirements.txt but had an error with installing **bunch**. Then some other install errors. My version of python is Python 3.12.5. The repo is [linked here](https://github.com/maxplush/ragnews). 

I first installed the requirements.txt file, ran into the bunch issue. So installed it separately. 
```
(venv) maxplush@Maxs-MacBook-Pro ragnews % pip install bunch
Collecting bunch
  Using cached bunch-1.0.1.zip (11 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/maxplush/Documents/ragnews/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/maxplush/Documents/ragnews/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/maxplush/Documents/ragnews/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/9f/nchgzy5d1bzfpjd_4m_20y600000gn/T/pip-build-env-c_j0t5i4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/9f/nchgzy5d1bzfpjd_4m_20y600000gn/T/pip-build-env-c_j0t5i4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/9f/nchgzy5d1bzfpjd_4m_20y600000gn/T/pip-build-env-c_j0t5i4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/9f/nchgzy5d1bzfpjd_4m_20y600000gn/T/pip-build-env-c_j0t5i4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
      ValueError: invalid mode: 'rU'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

When I commented out bunch from my requirements.txt file and tried to reinstall to see if other packages were also not being installed I got this error as well.
```
 (venv) maxplush@Maxs-MacBook-Pro ragnews % pip install -r requirements.txt 
Requirement already satisfied: annotated-types==0.7.0 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (0.7.0)
Requirement already satisfied: anyio==4.4.0 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 2)) (4.4.0)
Collecting asn1crypto==0.24.0 (from -r requirements.txt (line 3))
  Using cached asn1crypto-0.24.0-py2.py3-none-any.whl.metadata (1.1 kB)
Collecting attrs==21.4.0 (from -r requirements.txt (line 4))
  Using cached attrs-21.4.0-py2.py3-none-any.whl.metadata (9.8 kB)
Collecting beautifulsoup4==4.9.3 (from -r requirements.txt (line 5))
  Using cached beautifulsoup4-4.9.3-py3-none-any.whl.metadata (4.2 kB)
Collecting certifi==2020.11.8 (from -r requirements.txt (line 7))
  Downloading certifi-2020.11.8-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting cffi==1.17.1 (from -r requirements.txt (line 8))
  Downloading cffi-1.17.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (1.5 kB)
Collecting chardet==3.0.4 (from -r requirements.txt (line 9))
  Downloading chardet-3.0.4-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting click==7.1.2 (from -r requirements.txt (line 10))
  Downloading click-7.1.2-py2.py3-none-any.whl.metadata (2.9 kB)
Collecting cryptography==2.6.1 (from -r requirements.txt (line 11))
  Downloading cryptography-2.6.1.tar.gz (491 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cssselect==1.2.0 (from -r requirements.txt (line 12))
  Downloading cssselect-1.2.0-py2.py3-none-any.whl.metadata (2.2 kB)
Collecting dateparser==1.2.0 (from -r requirements.txt (line 13))
  Downloading dateparser-1.2.0-py2.py3-none-any.whl.metadata (28 kB)
Requirement already satisfied: distro==1.9.0 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 14)) (1.9.0)
Collecting exceptiongroup==1.2.2 (from -r requirements.txt (line 15))
  Downloading exceptiongroup-1.2.2-py3-none-any.whl.metadata (6.6 kB)
Collecting filelock==3.0.12 (from -r requirements.txt (line 16))
  Downloading filelock-3.0.12-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: groq==0.11.0 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 17)) (0.11.0)
Requirement already satisfied: h11==0.14.0 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 18)) (0.14.0)
Requirement already satisfied: httpcore==1.0.5 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 19)) (1.0.5)
Requirement already satisfied: httpx==0.27.2 in ./venv/lib/python3.12/site-packages (from -r requirements.txt (line 20)) (0.27.2)
Collecting idna==2.10 (from -r requirements.txt (line 21))
  Downloading idna-2.10-py2.py3-none-any.whl.metadata (9.1 kB)
Collecting joblib==0.17.0 (from -r requirements.txt (line 22))
  Downloading joblib-0.17.0-py3-none-any.whl.metadata (4.5 kB)
Collecting jsonpath-ng==1.6.1 (from -r requirements.txt (line 23))
  Downloading jsonpath_ng-1.6.1-py3-none-any.whl.metadata (18 kB)
Collecting langid==1.1.6 (from -r requirements.txt (line 24))
  Downloading langid-1.1.6.tar.gz (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 29.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting lxml==5.3.0 (from -r requirements.txt (line 25))
  Using cached lxml-5.3.0-cp312-cp312-macosx_10_9_universal2.whl.metadata (3.8 kB)
Collecting lxml-html-clean==0.2.2 (from -r requirements.txt (line 26))
  Downloading lxml_html_clean-0.2.2-py3-none-any.whl.metadata (1.8 kB)
ERROR: Could not find a version that satisfies the requirement metahtml==0.0.1.dev0 (from versions: none)
ERROR: No matching distribution found for metahtml==0.0.1.dev0
```

Since these packages are not installed. When I tried to test my ragnews.py, the terminal line did open but did not return any values when I asked a question. Where did I go wrong for this set up?

```
(venv) maxplush@Maxs-MacBook-Pro ragnews % python3 ragnews.py             
ragnews> who is the us pres?
None
```

**Comment by ains-arch** [comment]
The issue here is that Mike's on Python 3.9.something [20, maybe? I don't think it's important] and therefore his `requirements.txt` works for his version of Python but not the current/near current one that you and I have installed. There are, I think, two general ways to approach solving this. Regardless, your current `venv` is probably in package dependency hell, so you should expect to remove it and start from scratch.

Approach one would be to make your environment look like Mike's, so his repo works [more] smoothly. This is what I've done. In order to do that, you must figure out how to install Python 3.9 and use it to spin up the virtual environment instead of the one currently mapped to python3.

For me [guy on Debian-based Linux], this looked like [adding the deadsnakes ppa and installing Python 3.9](https://stackoverflow.com/questions/70422866/how-to-create-a-venv-with-a-different-python-version) support through that. The exact commands I ran are currently in my [ragnews](https://github.com/ains-arch/ragnews/) README. For you, it might look something like [using `homebrew` and `pyenv`](https://stackoverflow.com/questions/71108232/how-to-switch-python3-versions-on-macos). There might be a better way to do this using `venv` or a different virtual environment/package management scheme.

Approach two would be to start from scratch[ish] on your environment so that it works with your already installed Python version, and rewrite what Mike has done to fit that. I think this is what he recommended us do in class. In this situation, it's probably easiest to start with a new environment, `pip install` Groq, and repeatedly run `ragnews.py` and install the other missing packages, allowing pip to manage the package dependencies and versioning. Then you can `pip freeze` your own `requirements.txt` that works with your Python version and go from there. This is probably easier than approach one, but I haven't tested it so I'm not sure.

**Comment by mikeizbicki** [comment]
Everything @ains-arch said is correct.  I have two things to add:

1. The "standard" / "easy" way to install multiple versions of python on a machine is using the command
    ```
    $ curl https://pyenv.run | bash
    ```
    This should "just work" on mac machines and windows machines that have a unix-like environment configured.  Details are at <https://github.com/pyenv/pyenv-installer>.

2. I've pushed the following commit https://github.com/mikeizbicki/ragnews/commit/a67bfd419d7e44c139a74ee1591b876b4fc87030 which should fix this problem so there is no need to install a new python version.  You should now be able to get the code to run with the commands:
    ```
    $ git pull origin master # to update your repo with the new code
    $ pip3 install groq
    $ python3
    >>> import ragnews
    >>> ragnews.extract_keywords( ... )
    ```
    Alternatively, the last shell command can be replaced with
    ```
    $ python3 -i ragnews.py
    ragnews>
    ```
    Notice that this does not put you directly in python, but instead into the `ragnews> ` prompt.  Pressing `^D` ends the `ragnews> ` prompt and dumps you back into interactive python with an error like:
    ```
    Traceback (most recent call last):
      File "/home/user/proj/ragnews/ragnews.py", line 372, in <module>
        text = input('ragnews> ')
    EOFError
    >>>
    ```

**Comment by mikeizbicki** [comment]
Actually, I'm just now noticing the last part of your message:

```
(venv) maxplush@Maxs-MacBook-Pro ragnews % python3 ragnews.py             
ragnews> who is the us pres?
None
```

This is expected behavior.  The code has a number of FIXME annotations, and so it won't work until you've completed those annotations.  We talked last time about how to complete the `extract_keywords` function, and tomorrow we'll talk about the remaining two.
