### ISSUE TITLE
Importing ragnews

### ISSUE THREAD

**Issue by aopsahl25** [mikeizbicki/cmc-csci181-languages#18]
I am getting the following error to my "import ragnews" command at the very top of my evaluate.py file:

```
Traceback (most recent call last):
  File "/Users/ameliaopsahl/ragnews/ragnews/evaluate.py", line 5, in <module>
    import ragnews
ModuleNotFoundError: No module named 'ragnews'
```

I have my evaluate.py file stored in my ragnews folder, which also has an __init__.py file. Any ideas on how to successfully import this folder as a module?

**Comment by mikeizbicki** [comment]
IIRC correctly, you use a Mac, right?

In the command line, run the command
```
$ export PYTHONPATH=.
```
Then, the code can be run with a command like
```
$ python3 -i ragnews/evaluate.py
```
The important part is that your working directory is the project root and not the `ragnews` folder.

On Windows, the instructions are a bit more complicated for setting `PYTHONPATH`: <https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-so-it-finds-my-modules-packages>

----


PS.  Filenames should be in backtick characters.  Thus `__init__.py` instead of __init__.py.  Notice how the latter is formatted awkwardly here and in your post.

**Comment by aopsahl25** [comment]
I am on Mac and that first command worked - thank you!
