### ISSUE TITLE
Project Proposals

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci181-languages#26]
This issue is for submitting your project proposals.  Before class next Wednesday 16 Oct, reply with:
1. The title
2. List of group members 
3. 2-5 sentence description of what you'll do
4. List of any references / links you'll use

**Comment by aopsahl25** [comment]
1. LMQL Tutorial
2. Working alone
3. For my final project, I will be making a LMQL tutorial in the form of a GitHub repository. The following are topics that I plan to cover in my tutorial: LMQL prompt construction and text generation (including constrained generation), model measuring (results classification and confidence scores), meta prompting, and potentially implementing chatbots with LMQL's interactive generation/results streaming. I will explain each of these topics individually and will also highlight ways that they interact. 
4. References: 
-- https://lmql.ai/
-- https://www.datacamp.com/tutorial/introduction-to-lmql
-- https://arxiv.org/pdf/2212.06094
-- https://medium.com/@abhishekranjandev/lmql-a-deep-dive-into-the-future-of-language-model-interaction-81297cf3ab2c
-- https://towardsdatascience.com/lmql-sql-for-language-models-d7486d88c541
-- https://wandb.ai/mostafaibrahim17/ml-articles/reports/Unveiling-LMQL-The-Future-of-Interacting-with-Language-Models--Vmlldzo2NzgzMjcy

**Comment by KentaWood** [comment]
1.**Project Title:** Fantasy (Football) Sports Assistant  
2.**Team:** Solo

3.**Project Description:**  
The project is a web app designed as an assistant for fantasy sports leagues, particularly focused on fantasy football. The app will provide personalized player recommendations based on real-time data such as player stats, injuries, and matchups. It will also offer AI-driven insights for drafting strategies and trade suggestions. A feature I was thinking of, was for users ti receive daily or weekly performance summaries and can interact with the assistant via a Q&A feature, helping them make informed decisions to optimize their fantasy teams.

4.**Potential APIs and Data Sources:**  
- **Yahoo Fantasy Sports API:** [Yahoo Fantasy Data](https://developer.yahoo.com/fantasysports/guide/?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAANmeznQhjTlqJRGZmgSg5iFDnrgbNLPOPLinoSJeSQqdm7nv_Bu0Qq2gmvQIm-PfvncolN2FeJKXs1xV_KGIR8yTSZB6MEbm99J8WCWnL-hUA7ZFhq8KbdmA_iW6nsoQfxPAjCxFdxe9zCrY_rSJsDVPQTVcc7WWgPNny8_KXAqq)  
- **ChatGPT API for AI insights:** [OpenAI API](https://platform.openai.com/docs/api-reference/making-requests)  
- **Sleeper Football Data API:** [Sleeper Football Data](https://docs.sleeper.com/)

**Comment by finnless** [comment]
1. **Title:** Build open-text social survey response coder library
2. **Team:** Nolan
3. **Project Description:** This project is a open source library that uses language models to code open-ended response questions often used in public opinion polling. The target audience for this project social science researches so the library will be easy to use. There will be features for setting a codebook, inputing survey responses, and validating the classifiers accuracy on manually label ground truth test data.
4. Links:
 - [Do AIs know what the most important issue is? Using language models to code open-text social survey responses at scale](https://doi.org/10.1177/20531680241231468)
 - [Automating Research in Business and Technical Communication: Large Language Models as Qualitative Coders](https://doi.org/10.1177/10506519241239927)
 - [An Examination of the Use of Large Language Models to Aid Analysis of Textual Data](https://doi.org/10.1177/16094069241231168)

Additional Links:
 - [Codebook LLMs: Adapting Political Science Codebooks for LLM Use and Adapting LLMs to Follow Codebooks](https://doi.org/10.48550/arXiv.2407.10747)
 - [Can Generative AI improve social science?](https://doi.org/10.1073/pnas.2314021121)

**Comment by albert-bpc** [comment]
Title: Financial Statement Generator
Team: Albert 
Project Description: Use LMQL to take financial data scraped from pdfs and insert the data into an excel model for the 3 financial statements. The target audience for this project are analysts who have to manually move numbers from unstructured documents into excel sheets. There will be a front end where the user can upload a zip file of pdfs and an excel file will be returned. 
Links: 
https://lmql.ai/docs/models/azure.html
https://azure.microsoft.com/en-us/products/ai-services/ai-document-intelligence
https://www.wallstreetprep.com/knowledge/financial-modeling/

**Comment by RuiZhangg** [comment]
1. **Title**: Course Recommandation Bot
2. **Group**: solo
3. **Description**: I plan to use the RAG and evaluation we have learned in the earlier part of the course to implement a chat that can respond to your question regarding course selection in 5C. I need to build a database for it, modify the prompts, and create a test set to evaluate its performance. 
4. **reference**: Topic01 and topic02

**Comment by EthanTu2** [comment]
Title: Medical Machine Translation Research Paper Implementation

Group: Solo

Description: I am currently writing a survey paper on medical machine translation publications since 2021. One of the things I will do for this paper will be done via this project: I plan to use my own data to implement an approach found in one of the research papers I like, experiment/innovate further, compare the results with those found in other papers in the field, and then decide whether the approach should be explored further. I am co-authoring this paper with a professor at CMC.

References: Topic04, Google Scholar, arXiv, PubMed

**Comment by ains-arch** [comment]
1. RAG for Pitzer IT Help Desk
1. me unless someone is secretly really interested in this topic
1. RAG system over Pitzer's public IT documentation. Run some kind of scraper over the relevant  parts of the Pitzer website, throw it into a RAG system, whip up some quick and dirty chatbot that one could hypothetically use to solve IT-related problems. Figure out if I can compare it to whatever Freshworks' version of this product is ([Freddy
   AI?](https://www.freshworks.com/platform/freddy-ai/). Encourage useful results... maybe have it pull from a larger database if the initial response isn't well received. Possibly give up and do something more interesting if I get bored.
1. [pitzercollege.freshservice.com](https://pitzercollege.freshservice.com/support/solutions/31000005373), [the rest of the IT section of the Pitzer website](https://www.pitzer.edu/offices/information-technology), RAG stuff from earlier in the semester

**Comment by mikeizbicki** [comment]
These projects look good as-is: @aopsahl25 @finnless @RuiZhangg @albert-bpc

@KentaWood 
1. It's not clear to me where the course-tie-in is.  The current way of doing sports analytics type stuff is standard machine learning algorithms like logistic regression.  Doing that wouldn't be enough.  You'll need to have something incorporating language.  One possibility is generating written responses off of the existing analytics, but it's not clear to me how to do this in a way that is actually providing value.
2. It's fine to incorporate your project into a webapp, but the webapp portion won't earn you credit for the course.  The important part for the course is that langauge backend components.
3. The phrase "AI-driven insights" is a marketing phrase that has no meaning and its use signals that the speaker is non-technical.  You should remove it from your vocabulary and in the future be more specific about what those insights are.

@EthanTu2 
This doesn't have enough course tie-in.  You need to somehow use language models to do something.  Some example possibilities include: (1) Use an LLM to implement a translation system.  (2) Write a chatbot that let's you chat with the research papers.  (3) If you go down the path of implementing another paper, you need to tell me exactly which paper you'll be implementing and what data you'll be using. 

@ains-arch I like the idea.  To be actually helpful for your given usecase, though, users would probably need to be able to upload screenshots.  So think about ways to include these screenshots in the chatbots as well.

**Comment by EthanTu2** [comment]
I like the 2nd option which is to write a chatbot that lets me chat with research papers. This will, in a sense, help me with understanding the different medical machine translation papers I have to read and understand.

Title: Good Research Paper Chatbot

Group: James Duong and Ethan Tu

Description: I plan to create a chatbot that can take a number of research papers via html scraping likely, and then answer any user query about regarding the research papers. This is relevant and cool because ChatGPT currently does not do a good job of reading and understanding papers in general (much less for research papers with figures). I might do some experimentation with helping the chatbot understand pictures better. I want to speak with Mike more at some point to gauge the feasibility of this project.

References: Topic01, Topic02, Research papers from Google Scholar, arXiv, PubMed

**Comment by abizermamnoon** [comment]
Title: CMC Course Recommender
Participant: solo

Project Overview: I will create a RAG model comprising CMC's economics and data science courses.  A user can provide the chatbot with their transcript. The chatbot will identify what courses the student can take given the courses they have already taken. The chatbot will also verify whether these courses are offered in the spring

References: 
https://catalog.claremontmckenna.edu/preview_entity.php?catoid=38&ent_oid=1542&returnto=7766
https://catalog.claremontmckenna.edu/preview_entity.php?catoid=38&ent_oid=1591&returnto=7766

**Comment by danzhechen** [comment]
Title: Leveraging LLMs for Efficient Emotion Analysis in Media Studies
Participant: Solo

Project Overview: This project aims to design a toolkit that utilizes LLMs to enhance the efficiency of emotion analysis within media studies. A significant part of media studies research involves dissecting and understanding the emotional undertones in text, including news articles, social media posts, and other textual content. 

Experimental Component: To ensure the effectiveness of this toolkit, the project will include an experimental component to evaluate the accuracy and behavior of the model. I will perform sentiment analysis on a selected corpus using both traditional methods and the new LLM-powered toolkit to compare results in terms of accuracy, efficiency, and ease of use.

Reference: https://www.sciencedirect.com/science/article/pii/S187705091931885X

**Comment by luisgomez214** [comment]
Title: AI-Powered Study Guide Generator Using RAG System

Group Members: Me (unless anyone wants to join) 

Description: This project will develop a system that helps students generate personalized study guides by retrieving relevant academic materials and providing concise summaries through a RAG model. The system will store educational content such as PDFs, textbooks, and notes in a custom database, allowing users to query the database for study materials related to specific topics. I plan on using html scraping and using python PDFS libraries to extract information. Using AI, the system will summarize key information and generate study guides or explanations, offering a dynamic tool for students to prepare for exams or assignments.


References/Links:
    •    Topic01 and Topic02
    •    Use my assignments / use free textbooks 
    •    https://ai.gopubby.com/lets-build-a-simple-educational-app-using-agentic-rag-all-local-85fc3bd5517a

**Comment by maxplush** [comment]
**Title**: Storytelling RAG System for Preserving Memories of Loved Ones

**Participant**: Max

**Description**:
This project aims to develop a tool that allows users to upload written stories about loved ones who have passed away, preserving their memories in a central database. These stories will be automatically tagged with relevant themes or keywords, making them easily searchable and categorized for future reference. The tool will feature a chat interface where users can input prompts or questions. Based on the keywords in the prompt, the system will retrieve and present the most relevant story from the database.

While the system will incorporate RAG techniques to ensure precise and contextually accurate story retrieval, the project will limit the use of LLM's for text generation to avoid altering or fabricating the stories. The goal is to maintain the integrity and authenticity of the uploaded stories, allowing users to engage with real memories rather than AI-generated content.

The aim is to create a meaningful platform for remembrance, where individuals can easily access and interact with stories about their loved ones, fostering a sense of connection through shared memories.

**References**:
- [Tavus](https://www.tavus.io/?utm_source=google&utm_medium=cpc&utm_campaign=&adgroup=&utm_content=&utm_term={matchtype)_tavus&network=g&device=c&placement=&gad_source=1&gclid=CjwKCAjw1NK4BhAwEiwAVUHPUONzpeqOy2h8vUua0BcCZ5tSpuDXRY6kCLDQEatZZH1kRnOHNGsPWBoC9cUQAvD_BwE) could be interesting to implement this also (stretch goal)
- RAG Topic

**Comment by alexcnsf** [comment]
Title: MasteryCards

Participant: Alex Nasoni

Description:
I create flashcards for almost all of my classes and I have found myself recently using ChatGPT to better summarise the key material for my flashcards and also wishing I would be able to make them quicker then having to manually writing them all out. So my plan is to develop a tool that automatically generates flashcard decks from educational materials such inputted textbooks, study guides, or personal notes pdfs using LLMs. The system will allow an input of study material and any specification on what the scope the flashcard should cover and it will extract key concepts, definitions, and questions to create a personalized set of flashcards. The goal is to make me be able to make flashcards for all of my classes quicker, have them be more thorough, and without constantly running out of blank flashcards. I think I use flashcards a lot because I learn best visually and iteratively and often find single-exposure to topics in lecture or from reading texts book to rarely create strong understanding of the topic for me. So because of this if I get far enough I would like to build on the system to include being able guess the answers to flashcards, use LLMs to score responses, and removing flashcards after a certain number of consecutive correct responses, so it could become an all around learning tool to judge mastery of the topic covered by the flashcards.

References:
1.  https://github.com/crybot/obsidian-flashcards-llm 
2.  https://github.com/ataguru/LLM-Flashcards-FastAPI
3.  GroqAI or other low-latency LLMs for answer grading

**Comment by luisgomez214** [comment]
Title: "Based on External Reviews" Chatbot for IMDB 

Members: Me

On IMDb, there is a section called "Reviews" where members share their ratings and written reviews of movies and shows. Another section, titled "External Reviews," provides links to other sites with additional reviews, but only as links, without offering users any immediate insights. My goal is to enhance this experience by creating a chatbot that users can interact with based on the content of these reviews. Think of Amazon and how when you look at an item, you can ask the chatbot about the item and it tells you information based on the reviews. This chatbot will use an LLM to summarize the reviews, translate them when necessary, and identify keywords, allowing it to effectively answer user questions about the movie or show. This approach will provide a richer, more accessible understanding of reviews without requiring users to navigate multiple external sites. To complete this, I plan on choosing a few movies that the chatbot will be able to answer. For the experimental component, I plan on testing the bot by asking it questions about the movie and seeing if key words are being shown. 

Links: 
Rag Topic01 and Topic02
Example https://www.imdb.com/title/tt7286456/externalreviews/?ref_=tturv_sa_4
