### ISSUE TITLE
infix_to_rpn Test case question for Arithmetic HW

### ISSUE THREAD

**Issue by RuiZhangg** [mikeizbicki/cmc-csci181-languages#35]
Hi, in the test cases for function `infix_to_rpn`, I am confused by the answer of test cases. 
For example, we have 
```
>>> infix_to_rpn('1-2')
    '1 2 -'
```
However, the result for `'1-2'` is -1, while the result for `'1 2 -'` is 1 according to test case in `eval_rpn`. Should the result for `infix_to_rpn('1-2')` be `'1 2 -'` or actually `'2 1 -'`? Thanks!

**Comment by mikeizbicki** [comment]
Eeek... I made a mistake!  (And thanks for pointing it out.)

`infix_to_rpn('1-2')` should be `1 2 -`.  My implementation of `eval_rpn` is incorrect. (I used the arguments in the wrong order.)

A better set of test cases that integrated both the `eval_rpn` and `infix_to_rpn` functions together would have caught this problem.  The correct way to implement this test case is using something called the `hypothesis` library in python, but I decided to forego this advanced testing since we hadn't talked about it in class.
