### ISSUE TITLE
Project Rubric 

### ISSUE THREAD

**Issue by albert-bpc** [mikeizbicki/cmc-csci181-languages#44]
[CSCI181 - Albert's Rubric.pdf](https://github.com/user-attachments/files/17653289/CSCI181.-.Albert.s.Rubric.pdf)

**Comment by mikeizbicki** [comment]
There are two points that could use clarifying:

You mention in T3 that you will ask questions via rag.  It's not clear to me exactly what the documents are that are going into the rag system, however.  If it's just the quarterly/annual reports, then it's not obvious to me that a rag system is actually needed.

You also don't currently have anything "experimental" where you are measuring your system's performance analytically.  If your LMQL system were sufficiently advanced, then I'd be willing to waive this requirement since LMQL can be thought of as giving you a "100%" coverage on certain types of tests.  But it's not clear to me exactly how you will be using LMQL here to constrain the model.  In particular, it's not obvious to me how LMQL can constrain the output to be "revenue - expenses must equal gross profit" or why you would even want the model to be independently calculating gross profit.  (If you already have revenue and expenses extracted by the model, then why not just manually calculate the profit yourself?
